from ghidra.app.script import GhidraScript

# setAnalysisOption(currentProgram, "PDB Universal", "false")
# setAnalysisOption(currentProgram, "Create Address Tables", "false")
# setAnalysisOption(currentProgram, "Create Address Tables - One Time", "false")
# setAnalysisOption(currentProgram, "Create Function", "false")
# setAnalysisOption(currentProgram, "Data Reference", "false")
# setAnalysisOption(currentProgram, "Demangler Microsoft", "false")
# setAnalysisOption(currentProgram, "Disassemble", "false")
# setAnalysisOption(currentProgram, "Disassemble Entry Points", "false")
# setAnalysisOption(currentProgram, "Function ID", "false")
# setAnalysisOption(currentProgram, "Function Start Search", "false")
# setAnalysisOption(currentProgram, "Function Start Search After Code", "false")
# setAnalysisOption(currentProgram, "Function Start Search After Data", "false")
# setAnalysisOption(
#    currentProgram, "Function Start Search delayed - One Time", "false")
# setAnalysisOption(
#    currentProgram, "Non - Returning Functions - Discovered", "false")
# setAnalysisOption(currentProgram, "Non - Returning Functions - Known", "false")
# setAnalysisOption(currentProgram, "Reference", "false")
# setAnalysisOption(currentProgram, "Subroutine References", "false")
# setAnalysisOption(currentProgram, "Subroutine References - One Time", "false")
# setAnalysisOption(currentProgram, "Windows x86 PE RTTI Analyzer", "false")
# setAnalysisOption(currentProgram, "X86 Function Callee Purge", "false")
# setAnalysisOption(currentProgram, "Call Convention ID", "false")
# setAnalysisOption(currentProgram, "Call - Fixup Installer", "false")
setAnalysisOption(currentProgram, "ASCII Strings", "false")
setAnalysisOption(currentProgram, "Apply Data Archives", "false")
setAnalysisOption(currentProgram, "Decompiler Switch Analysis", "false")
setAnalysisOption(currentProgram, "Decompiler Parameter ID", "false")
setAnalysisOption(currentProgram, "Embedded Media", "false")
setAnalysisOption(currentProgram, "External Entry References", "false")
setAnalysisOption(currentProgram, "Scalar Operand References", "false")
setAnalysisOption(currentProgram, "Shared Return Calls", "false")
setAnalysisOption(currentProgram, "Stack", "false")
setAnalysisOption(currentProgram, "Windows x86 PE Exception Handling", "false")
# setAnalysisOption(currentProgram, "WindowsResourceReference", "false")
# setAnalysisOption(currentProgram, "x86 Constant Reference Analyzer", "false")
